# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'C41Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for C41Demo
  target 'C41DemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mantle'
    pod 'FMDB'
    pod 'YDPreventCrash', '3.1.1'
    
  end

  target 'C41DemoUITests' do
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    
  end

end
